### ISSUE TITLE
No Timeout on ReadPassiveTarget - it limits possibilities

### ISSUE THREAD

**Issue by deddokatana** [adafruit/Adafruit_NFCShield_I2C#17]
as ive read so far, there is no timeout (to return false) for the read passive target function, this is good for default feature, but a timeout is also needed for other things such as allowing a loop to continue to allow printing to lcd regardless of card input.

suggested behaviour:
if timeout specified in the perameters (brackets) :
nfc.ReadPassiveTarget(mandetoryStuff,int timeout in ms).
since there is no feature request on github, id like to file it here.
wonderful product but i need some more done to the code.. i can contribute if need be.

**Comment by tdicola** [comment]
Apologies this went so long without a response, but we've just cleaned up this NFCShield_I2C library and integrated it into the PN532 library here: https://github.com/adafruit/Adafruit-PN532

It looks like the PN532 readPassiveTarget API now has an optional timeout parameter, check it out here: https://github.com/adafruit/Adafruit-PN532/blob/master/Adafruit_PN532.h#L170  Pass a timeout value in milliseconds as the optional last parameter and it should fail after that amount of time without finding a target.  Thanks for suggesting the change!
