### ISSUE TITLE
No delay needed between Wire.read() after a Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_NFCShield_I2C#23]
In the file "Adafruit_NFCShield_I2C/Adafruit_NFCShield_I2C.cpp" in the function `wirereaddata()`, there is a `delay(1)` (at the moment in line 985) in the for-loop when reading data.

That delay may be removed.
The data is put into a buffer by the `Wire.requestFrom()`. After the I2C bus transaction has finished, the `Wire.read()` reads data from that buffer. There is no need to have a delay to get data from a buffer.

**Comment by ladyada** [comment]
thanks - this repo is totally deprecated and unsupported, we're not only using our main PN532 library!
